## Note: gradle plugins like userdev or run-paper can't get an entry here because of kotlin's limitations.
# Project meta
pluginVersion=2.0.3
release=false
group=au.com.mineauz
mcVersion=1.21.4
javaVersion=21
caffeineVersion=3.2.2
simpleQuestsVersion=2.0.0
commons-collections4Version=4.5.0
## Note: the first is the maven api version, the second the wierd modrinth id
### this is the api to compile against
worldguardVersion=7.0.14-SNAPSHOT
### this is the ready to use .jar used in the run task
worldeditVersionRunTask=Jk1z2u7n
worldguardVersionRunTask=f9NoeotB
# Gradle configuration
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
