main: de.greensurvivors.greenplugin.GreenPlugin
name: GreenPlugin
api-version: '${apiVersion}'
version: ${version}
description: ${description}
author: GreensurvivorsTeam

commands:
  greenplugin:
    description: A command.