main: de.greensurvivors.eventhelper.Eventhelper
name: Eventhelper
api-version: '${mainMCVersion}'
version: ${version}
description: ${description}
author: GreensurvivorsTeam
loadbefore:
  - WorldGuard

commands:
  eventhelper:
    description: A command.