main: de.greensurvivors.eventhelper.EventHelper
name: EventHelper
api-version: '${mainMCVersion}'
version: ${version}
description: ${description}
author: GreensurvivorsTeam
loadbefore:
  - WorldGuard
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
# commands are registered with their permissions in code